apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
        - name: postgresdb
          image: seeis/sensor-postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: postgres-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          readinessProbe:
            exec:
              command:
                ["psql", "-U", "admin", "-d", "sensordb", "-c", "SELECT 1"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command:
                ["psql", "-U", "admin", "-d", "sensordb", "-c", "SELECT 1"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
