version: "3.8"
services:
  influxdb:
    image: "influxdb:2.0"
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-conf:/etc/influxdb2
    env_file:
      - ./composer-env/influx.env
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure:5

  postgresdb:
    build: ./postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./composer-env/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/pg_isready -U admin -d sensordb"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      influxdb:
        condition: service_healthy
    restart: on-failure:5

  backend:
    build: ../../backend
    env_file:
      - ./composer-env/backend.env
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - backend-logs:/backend/sensor.log
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: on-failure:5

  cli:
    build: ../../cli
    env_file:
      - ./composer-env/cli.env
    volumes:
      - cli-logs:/var/lib/sensor.log
    depends_on:
      - backend

volumes:
  postgres-data:
  influx-data:
  influx-conf:
  backend-logs:
  cli-logs:
